Add controllers
IAmA1ex/java-shareit pull request #1
Opened 2024-06-30 21:12 UTC by IAmA1ex

2024-07-01 19:20 UTC, z8q requested changes

2024-07-01 19:20 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @Valid @RequestBody Item item) {
Принимать тоже стоит Dto,
Потом, когда model станет jpa-entity, она будет использоваться только для работы с базой, описания таблиц и зависимостей меджу таблицами.
По логике приложения будет ходить только дто

2024-07-01 19:20 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Email(message = "Почта имеет неверный формат.")
Валидационные аннотации нужно перенести на dto, 
модели будут выполнять роль jpa-сущностей в последующщих домашках

2024-07-01 20:53 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final MapperItemDto mapperItemDto;
Я ориентировался на статью представленную тут https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application. Тут Использован подход преобразования в dto в контроллере. Напиши потом, пожалуйста, почему реализовали так и почему надо переносить в сервис кроме того что это логика. Хотелось бы разобраться в практичности каждого подхода.

2024-07-02 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final MapperItemDto mapperItemDto;
Допустимы оба способа.
Момент субъективный и обычно просто в командах договариваются, будут ли что-то использовать в контроллерах или нет.
Я не рекомендую, чтобы все моменты логики были в сервисах, и не приходилось ходить между слоями.
Что-то вроде принципа единой ответственности
- контроллер отвечает за прием запроса, отправку ответа
- сервисы выполняют логику
- слой репозиториев ответственный за взаимодействие с бд

2024-07-02 18:18 UTC, z8q approved these changes

2024-07-14 16:17 UTC, merged