Add bookings
IAmA1ex/java-shareit pull request #2
Opened 2024-07-17 19:08 UTC by IAmA1ex

2024-07-18 20:14 UTC, z8q requested changes

2024-07-18 20:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingDto> getBookingsSlash(@RequestHeader("X-Sharer-User-Id") Long userId,
есть ли необходимость в этом методе?
выше в 42-й строке, если не передадим state, у нас применится all

2024-07-18 20:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        itemRepository.save(bookingItem);
Для чего сохранять item? Поля у него не изменяем, нового не создаем

2024-07-18 20:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public boolean bookingTimeIsCorrect(BookingDtoShort bookingDtoShort) {
методы, которые вызываем только внутри класса, нужно сделать приватными

2024-07-18 20:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Использование Data(содержит equals, hashCode, toString) в jpa-сущностях не приветствуется. В дипломе будут проверять.
можно почитать [тут](https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/) и [тут](https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/)

2024-07-18 20:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            throw new RuntimeException("Ошибка при создании пользователя.");
либо еще можно бросить какой-нибудь один вид кастомного исключения, перехватить в exception handler
и с наполнением сообщения в исключении уже там работать

2024-07-19 22:42 UTC, IAmA1ex commented on src/main/resources/schema.sql
> +    owner_user BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
remove booking owner

2024-07-20 00:11 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            throw new RuntimeException("Ошибка при создании пользователя.");
user email catch

2024-07-20 00:42 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        Optional<User> optOldUser = userRepository.findById(id);
short get object and check

2024-07-20 00:44 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        itemRepository.save(bookingItem);
save item

2024-07-20 00:48 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public boolean bookingTimeIsCorrect(BookingDtoShort bookingDtoShort) {
private

2024-07-20 00:53 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<BookingDto> getBookingsSlash(@RequestHeader("X-Sharer-User-Id") Long userId,
replace @Date with @Getter and @Setter

2024-07-20 01:06 UTC, IAmA1ex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private BookingStatus status;
как таковой прямой необходимости нет, но без него у меня не проходит тест _**Booking get all for wrong user 100**_ так как там в _URL_ стоит '/' и из-за этого Spring-у нужен еще один эндпоинт. Я понимаю что это выглядит максимально глупо, и что это какой-то костыль, но без него у меня не работает. 

Да, тест проходит потому что приходит ошибка 404, но она приходит не из-за того что объект не найден, а из-за того что не найден такой эндпоинт. Мне такое "удачное" стечение обстоятельств не нравится и я хочу чтобы выводились нужные сообщения об ошибках

В общем я не очень понимаю как решить эту проблему, поэтому такой вот костыль получился

2024-07-20 01:14 UTC, IAmA1ex commented on src/main/resources/schema.sql
> +    owner_user BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
Да, я знаю, я изучал этот вопрос, но мне в таком подходе не нравится, что нарушается нормальная форма бд, поэтому я решил так оставить. Не знаю на самом деле как лучше, но как будто при любом способе выглядит не совсем правильным чтоли

2024-07-21 10:59 UTC, z8q approved these changes

2024-07-22 08:47 UTC, merged